### ISSUE TITLE
Add parser for MySQL audit log

### ISSUE THREAD

**Issue by vadimtk** [Altinity/clicktail#1]
Please add the parser for MySQL (Percona Server) audit logs.

We can start with just JSON format for now.

The install info:
https://www.percona.com/doc/percona-server/LATEST/management/audit_log_plugin.html#audit_log_format

**Comment by vadimtk** [comment]
example of audit log records
https://gist.github.com/vadimtk/dc336e745a0f81d7822deac7b15d7828

**Comment by amonakhov** [comment]
Hi Vadim,

Thanks for suggestion. It's done here https://github.com/Altinity/clicktail/commit/52ed31fe12ef94d1aec78c080b2f1ef2e4730e69
