### ISSUE TITLE
Error Loading Multiple MySQL Slow Log Files from a Directory using Clicktail

### ISSUE THREAD

**Issue by singla26** [Altinity/clicktail#6]
I am trying to load multiple MySQL Slow Log Files from a directory using Clicktail into ClickHouse.

For Ex:
Directory- /home/logs/
Log Files available in /home/logs/- 
            1. slow-query_1.25-02-2019
            2. slow-query_2.25-02-2019
            3. slow-query_3.25-02-2019
When I try to parse it using-      clicktail -p mysql -f /home/logs/* -d clicktail.mysql_slow_log
It parse it as- clicktail -p mysql -f /home/logs/slow-query_1.25-02-2019 /home/logs/slow-query_2.25-02-2019 /home/logs/slow-query_2.25-02-2019 -d clicktail.mysql_slow_log
and it gives error- "Unexpected parameter"

**Comment by amonakhov** [comment]
Hello singla26.

This is not clicktail parsing it to a list of files it is you operating system. You need to escape the path with quotes in order to get glob-alike pattern be passed properly to clicktail.
