### ISSUE TITLE
There is No Switch for Passing ClickHouse DB Password by ClickTail

### ISSUE THREAD

**Issue by imomo86** [Altinity/clicktail#7]
when ClickHouse DB has password authentication, a password must be sent by Clicktail, by I couldn't find any switch for passing password by Clicktail.

for ex:
sudo clicktail -p nginx -f /var/log/nginx/access.log -d clicktail.nginx_log --nginx.conf=/etc/nginx/nginx.conf --nginx.format=combined

response from server:
Could not connect to ClickHouse server:  ClickHouse server rejected authentication

**Comment by amonakhov** [comment]
Hello mofard,

You don't need a switch in order to connect to password-locked DB. You can use APIHost parameter for that matter (see clicktail.conf).

Example:

```
[Application Options]
; APIHost = http://changeuser:changepass@localhost:8123/
```

you can also use api_host parameter from CLI.

**Comment by imomo86** [comment]
Thanks a million, it's works,
but it's not mentioned in clicktail.conf
